/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommonConvertersIndexRouteImport } from './routes/common-converters.index'
import { Route as CommonConvertersLengthConverterIndexRouteImport } from './routes/common-converters.length-converter.index'
import { Route as CommonConvertersLengthConverterPairRouteImport } from './routes/common-converters.length-converter.$pair'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonConvertersIndexRoute = CommonConvertersIndexRouteImport.update({
  id: '/common-converters/',
  path: '/common-converters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonConvertersLengthConverterIndexRoute =
  CommonConvertersLengthConverterIndexRouteImport.update({
    id: '/common-converters/length-converter/',
    path: '/common-converters/length-converter/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommonConvertersLengthConverterPairRoute =
  CommonConvertersLengthConverterPairRouteImport.update({
    id: '/common-converters/length-converter/$pair',
    path: '/common-converters/length-converter/$pair',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/common-converters/': typeof CommonConvertersIndexRoute
  '/common-converters/length-converter/$pair': typeof CommonConvertersLengthConverterPairRoute
  '/common-converters/length-converter/': typeof CommonConvertersLengthConverterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/common-converters': typeof CommonConvertersIndexRoute
  '/common-converters/length-converter/$pair': typeof CommonConvertersLengthConverterPairRoute
  '/common-converters/length-converter': typeof CommonConvertersLengthConverterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/common-converters/': typeof CommonConvertersIndexRoute
  '/common-converters/length-converter/$pair': typeof CommonConvertersLengthConverterPairRoute
  '/common-converters/length-converter/': typeof CommonConvertersLengthConverterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/common-converters/'
    | '/common-converters/length-converter/$pair'
    | '/common-converters/length-converter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/common-converters'
    | '/common-converters/length-converter/$pair'
    | '/common-converters/length-converter'
  id:
    | '__root__'
    | '/'
    | '/common-converters/'
    | '/common-converters/length-converter/$pair'
    | '/common-converters/length-converter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommonConvertersIndexRoute: typeof CommonConvertersIndexRoute
  CommonConvertersLengthConverterPairRoute: typeof CommonConvertersLengthConverterPairRoute
  CommonConvertersLengthConverterIndexRoute: typeof CommonConvertersLengthConverterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/': {
      id: '/common-converters/'
      path: '/common-converters'
      fullPath: '/common-converters/'
      preLoaderRoute: typeof CommonConvertersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/length-converter/': {
      id: '/common-converters/length-converter/'
      path: '/common-converters/length-converter'
      fullPath: '/common-converters/length-converter/'
      preLoaderRoute: typeof CommonConvertersLengthConverterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/length-converter/$pair': {
      id: '/common-converters/length-converter/$pair'
      path: '/common-converters/length-converter/$pair'
      fullPath: '/common-converters/length-converter/$pair'
      preLoaderRoute: typeof CommonConvertersLengthConverterPairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommonConvertersIndexRoute: CommonConvertersIndexRoute,
  CommonConvertersLengthConverterPairRoute:
    CommonConvertersLengthConverterPairRoute,
  CommonConvertersLengthConverterIndexRoute:
    CommonConvertersLengthConverterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
