/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommonConvertersIndexRouteImport } from './routes/common-converters.index'
import { Route as CommonConvertersLengthConverterRouteImport } from './routes/common-converters.length-converter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonConvertersIndexRoute = CommonConvertersIndexRouteImport.update({
  id: '/common-converters/',
  path: '/common-converters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonConvertersLengthConverterRoute =
  CommonConvertersLengthConverterRouteImport.update({
    id: '/common-converters/length-converter',
    path: '/common-converters/length-converter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/common-converters/length-converter': typeof CommonConvertersLengthConverterRoute
  '/common-converters/': typeof CommonConvertersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/common-converters/length-converter': typeof CommonConvertersLengthConverterRoute
  '/common-converters': typeof CommonConvertersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/common-converters/length-converter': typeof CommonConvertersLengthConverterRoute
  '/common-converters/': typeof CommonConvertersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/common-converters/length-converter' | '/common-converters/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/common-converters/length-converter' | '/common-converters'
  id:
    | '__root__'
    | '/'
    | '/common-converters/length-converter'
    | '/common-converters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommonConvertersLengthConverterRoute: typeof CommonConvertersLengthConverterRoute
  CommonConvertersIndexRoute: typeof CommonConvertersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/': {
      id: '/common-converters/'
      path: '/common-converters'
      fullPath: '/common-converters/'
      preLoaderRoute: typeof CommonConvertersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/length-converter': {
      id: '/common-converters/length-converter'
      path: '/common-converters/length-converter'
      fullPath: '/common-converters/length-converter'
      preLoaderRoute: typeof CommonConvertersLengthConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommonConvertersLengthConverterRoute: CommonConvertersLengthConverterRoute,
  CommonConvertersIndexRoute: CommonConvertersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
