/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CommonConvertersIndexRouteImport } from './routes/common-converters.index'
import { Route as CommonConvertersAngleConverterIndexRouteImport } from './routes/common-converters.angle-converter.index'
import { Route as CommonConvertersAngleConverterPairRouteImport } from './routes/common-converters.angle-converter.$pair'
import { Route as CommonConvertersAreaConverterIndexRouteImport } from './routes/common-converters.area-converter.index'
import { Route as CommonConvertersAreaConverterPairRouteImport } from './routes/common-converters.area-converter.$pair'
import { Route as CommonConvertersLengthConverterIndexRouteImport } from './routes/common-converters.length-converter.index'
import { Route as CommonConvertersLengthConverterPairRouteImport } from './routes/common-converters.length-converter.$pair'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonConvertersIndexRoute = CommonConvertersIndexRouteImport.update({
  id: '/common-converters/',
  path: '/common-converters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonConvertersAngleConverterIndexRoute =
  CommonConvertersAngleConverterIndexRouteImport.update({
    id: '/common-converters/angle-converter/',
    path: '/common-converters/angle-converter/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommonConvertersAngleConverterPairRoute =
  CommonConvertersAngleConverterPairRouteImport.update({
    id: '/common-converters/angle-converter/$pair',
    path: '/common-converters/angle-converter/$pair',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommonConvertersAreaConverterIndexRoute =
  CommonConvertersAreaConverterIndexRouteImport.update({
    id: '/common-converters/area-converter/',
    path: '/common-converters/area-converter/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommonConvertersAreaConverterPairRoute =
  CommonConvertersAreaConverterPairRouteImport.update({
    id: '/common-converters/area-converter/$pair',
    path: '/common-converters/area-converter/$pair',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommonConvertersLengthConverterIndexRoute =
  CommonConvertersLengthConverterIndexRouteImport.update({
    id: '/common-converters/length-converter/',
    path: '/common-converters/length-converter/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommonConvertersLengthConverterPairRoute =
  CommonConvertersLengthConverterPairRouteImport.update({
    id: '/common-converters/length-converter/$pair',
    path: '/common-converters/length-converter/$pair',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/common-converters/': typeof CommonConvertersIndexRoute
  '/common-converters/angle-converter/$pair': typeof CommonConvertersAngleConverterPairRoute
  '/common-converters/area-converter/$pair': typeof CommonConvertersAreaConverterPairRoute
  '/common-converters/length-converter/$pair': typeof CommonConvertersLengthConverterPairRoute
  '/common-converters/angle-converter/': typeof CommonConvertersAngleConverterIndexRoute
  '/common-converters/area-converter/': typeof CommonConvertersAreaConverterIndexRoute
  '/common-converters/length-converter/': typeof CommonConvertersLengthConverterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/common-converters': typeof CommonConvertersIndexRoute
  '/common-converters/angle-converter/$pair': typeof CommonConvertersAngleConverterPairRoute
  '/common-converters/area-converter/$pair': typeof CommonConvertersAreaConverterPairRoute
  '/common-converters/length-converter/$pair': typeof CommonConvertersLengthConverterPairRoute
  '/common-converters/angle-converter': typeof CommonConvertersAngleConverterIndexRoute
  '/common-converters/area-converter': typeof CommonConvertersAreaConverterIndexRoute
  '/common-converters/length-converter': typeof CommonConvertersLengthConverterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/common-converters/': typeof CommonConvertersIndexRoute
  '/common-converters/angle-converter/$pair': typeof CommonConvertersAngleConverterPairRoute
  '/common-converters/area-converter/$pair': typeof CommonConvertersAreaConverterPairRoute
  '/common-converters/length-converter/$pair': typeof CommonConvertersLengthConverterPairRoute
  '/common-converters/angle-converter/': typeof CommonConvertersAngleConverterIndexRoute
  '/common-converters/area-converter/': typeof CommonConvertersAreaConverterIndexRoute
  '/common-converters/length-converter/': typeof CommonConvertersLengthConverterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/common-converters/'
    | '/common-converters/angle-converter/$pair'
    | '/common-converters/area-converter/$pair'
    | '/common-converters/length-converter/$pair'
    | '/common-converters/angle-converter/'
    | '/common-converters/area-converter/'
    | '/common-converters/length-converter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/common-converters'
    | '/common-converters/angle-converter/$pair'
    | '/common-converters/area-converter/$pair'
    | '/common-converters/length-converter/$pair'
    | '/common-converters/angle-converter'
    | '/common-converters/area-converter'
    | '/common-converters/length-converter'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/common-converters/'
    | '/common-converters/angle-converter/$pair'
    | '/common-converters/area-converter/$pair'
    | '/common-converters/length-converter/$pair'
    | '/common-converters/angle-converter/'
    | '/common-converters/area-converter/'
    | '/common-converters/length-converter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CommonConvertersIndexRoute: typeof CommonConvertersIndexRoute
  CommonConvertersAngleConverterPairRoute: typeof CommonConvertersAngleConverterPairRoute
  CommonConvertersAreaConverterPairRoute: typeof CommonConvertersAreaConverterPairRoute
  CommonConvertersLengthConverterPairRoute: typeof CommonConvertersLengthConverterPairRoute
  CommonConvertersAngleConverterIndexRoute: typeof CommonConvertersAngleConverterIndexRoute
  CommonConvertersAreaConverterIndexRoute: typeof CommonConvertersAreaConverterIndexRoute
  CommonConvertersLengthConverterIndexRoute: typeof CommonConvertersLengthConverterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/': {
      id: '/common-converters/'
      path: '/common-converters'
      fullPath: '/common-converters/'
      preLoaderRoute: typeof CommonConvertersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/angle-converter/': {
      id: '/common-converters/angle-converter/'
      path: '/common-converters/angle-converter'
      fullPath: '/common-converters/angle-converter/'
      preLoaderRoute: typeof CommonConvertersAngleConverterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/angle-converter/$pair': {
      id: '/common-converters/angle-converter/$pair'
      path: '/common-converters/angle-converter/$pair'
      fullPath: '/common-converters/angle-converter/$pair'
      preLoaderRoute: typeof CommonConvertersAngleConverterPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/area-converter/': {
      id: '/common-converters/area-converter/'
      path: '/common-converters/area-converter'
      fullPath: '/common-converters/area-converter/'
      preLoaderRoute: typeof CommonConvertersAreaConverterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/area-converter/$pair': {
      id: '/common-converters/area-converter/$pair'
      path: '/common-converters/area-converter/$pair'
      fullPath: '/common-converters/area-converter/$pair'
      preLoaderRoute: typeof CommonConvertersAreaConverterPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/length-converter/': {
      id: '/common-converters/length-converter/'
      path: '/common-converters/length-converter'
      fullPath: '/common-converters/length-converter/'
      preLoaderRoute: typeof CommonConvertersLengthConverterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-converters/length-converter/$pair': {
      id: '/common-converters/length-converter/$pair'
      path: '/common-converters/length-converter/$pair'
      fullPath: '/common-converters/length-converter/$pair'
      preLoaderRoute: typeof CommonConvertersLengthConverterPairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CommonConvertersIndexRoute: CommonConvertersIndexRoute,
  CommonConvertersAngleConverterPairRoute:
    CommonConvertersAngleConverterPairRoute,
  CommonConvertersAreaConverterPairRoute:
    CommonConvertersAreaConverterPairRoute,
  CommonConvertersLengthConverterPairRoute:
    CommonConvertersLengthConverterPairRoute,
  CommonConvertersAngleConverterIndexRoute:
    CommonConvertersAngleConverterIndexRoute,
  CommonConvertersAreaConverterIndexRoute:
    CommonConvertersAreaConverterIndexRoute,
  CommonConvertersLengthConverterIndexRoute:
    CommonConvertersLengthConverterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
